[project]
name = "fastapi-movies-catalog"
version = "0.1.0"
description = "Fastapi movies catalog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
